apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  path: ./kubernetes/cnpg-system/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg
  prune: false
  wait: true
  interval: 10m