apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: aws-secret
            - secretRef:
                name: database-secret
            - secretRef:
                  name: jwt-secret
          image: us-west1-docker.pkg.dev/kubernetes-cluster-458203/project-store/backend:1.6
          name: project-store-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gcp-artifact-registry
      restartPolicy: Always
