apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DB_USER: postgres
  DB_HOST: database
  DB_PASSWORD: postgres
  DB_NAME: projectStoreDB
  REDIS_URL: http://redis.default.svc.cluster.local:6379
  BACKEND_URL: http://backend.default.svc.cluster.local:8080