apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 32343
  selector:
    app: frontend
  type: NodePort


