apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: config
          image: frontend
          name: project-store-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
