apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium
  namespace: flux-system
spec:
  path: ./kubernetes/kube-system/metrics-server/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: metrics-server
  prune: false
  wait: true
  interval: 10m