apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 30m
  values:
    args:
      - --kubelet-insecure-tls