apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: dragonfly-operator-system
      namespace: flux-system
  path: ./kubernetes/dragonfly/cluster
  targetNamespace: dragonfly
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 10m