apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator-system-ks
  namespace: flux-system
spec:
  path: ./kubernetes/dragonfly-operator-system/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly-operator
  prune: false
  wait: true
  interval: 10m