apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium-netpols
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-system-cilium
      namespace: flux-system
  path: ./kubernetes/kube-system/cilium/netpols
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium
  prune: false
  wait: true
  interval: 10m